### Week 2 Exercise Solutions

In [95]:
import pandas as pd

In [96]:
base_url = "C:/Users/M E L S A/Desktop/M E L S A/data_science/datasciencetemp/data/covid/"
infected_dataset_url = base_url + "time_series_covid19_confirmed_global.csv"
recovered_dataset_url = base_url + "time_series_covid19_recovered_global.csv"
deaths_dataset_url = base_url + "time_series_covid19_deaths_global.csv"

In [97]:
infected_data_frame
# infected_data_frame.columns
# infected_data_frame.info
# infected_data_frame.describe()
# infected_data_frame.size
# infected_data_frame.shape
# infected_data_frame.dtypes
# infected_data_frame.values
# infected_data_frame.index

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,6/6/20,6/7/20,6/8/20,6/9/20,6/10/20,6/11/20,6/12/20,6/13/20,6/14/20,6/15/20
0,NaN,Afghanistan,33.000000,65.000000,0,0,0,0,0,0,...,19551,20342,20917,21459,22142,22890,23546,24102,24766,25527
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,1232,1246,1263,1299,1341,1385,1416,1464,1521,1590
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,10050,10154,10265,10382,10484,10589,10698,10810,10919,11031
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,852,852,852,852,852,852,853,853,853,853
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,88,91,92,96,113,118,130,138,140,142
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,NaN,Sao Tome and Principe,0.186360,6.613081,0,0,0,0,0,0,...,499,513,513,514,611,632,639,659,661,662
262,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,482,484,496,524,560,591,632,705,728,844
263,NaN,Comoros,-11.645500,43.333300,0,0,0,0,0,0,...,141,141,141,141,162,162,163,176,176,176
264,NaN,Tajikistan,38.861034,71.276093,0,0,0,0,0,0,...,4453,4529,4609,4690,4763,4834,4902,4971,5035,5097
265,NaN,Lesotho,-29.609988,28.233608,0,0,0,0,0,0,...,4,4,4,4,4,4,4,4,4,4

In [98]:
infected_data_frame = pd.read_csv(infected_dataset_url) #url yi oku ve DataFrame objesine ata
print(infected_data_frame.head())

  Province/State Country/Region      Lat     Long  1/22/20  1/23/20  1/24/20  \
0            NaN    Afghanistan  33.0000  65.0000        0        0        0
1            NaN        Albania  41.1533  20.1683        0        0        0
2            NaN        Algeria  28.0339   1.6596        0        0        0
3            NaN        Andorra  42.5063   1.5218        0        0        0
4            NaN         Angola -11.2027  17.8739        0        0        0

   1/25/20  1/26/20  1/27/20  ...  6/6/20  6/7/20  6/8/20  6/9/20  6/10/20  \
0        0        0        0  ...   19551   20342   20917   21459    22142
1        0        0        0  ...    1232    1246    1263    1299     1341
2        0        0        0  ...   10050   10154   10265   10382    10484
3        0        0        0  ...     852     852     852     852      852
4        0        0        0  ...      88      91      92      96      113

   6/11/20  6/12/20  6/13/20  6/14/20  6/15/20
0    22890    23546    24102    24766    25527
1     1385     1416     1464     1521     1590
2    10589    10698    10810    10919    11031
3      852      853      853      853      853
4      118      130      138      140      142

[5 rows x 150 columns]

In [99]:
recovered_data_frame = pd.read_csv(recovered_dataset_url)
print(recovered_data_frame.head())

  Province/State Country/Region      Lat     Long  1/22/20  1/23/20  1/24/20  \
0            NaN    Afghanistan  33.0000  65.0000        0        0        0
1            NaN        Albania  41.1533  20.1683        0        0        0
2            NaN        Algeria  28.0339   1.6596        0        0        0
3            NaN        Andorra  42.5063   1.5218        0        0        0
4            NaN         Angola -11.2027  17.8739        0        0        0

   1/25/20  1/26/20  1/27/20  ...  6/6/20  6/7/20  6/8/20  6/9/20  6/10/20  \
0        0        0        0  ...    1830    1875    2171    2651     3013
1        0        0        0  ...     925     938     945     960      980
2        0        0        0  ...    6631    6717    6799    6951     7074
3        0        0        0  ...     741     744     751     757      759
4        0        0        0  ...      24      24      38      38       40

   6/11/20  6/12/20  6/13/20  6/14/20  6/15/20
0     3326     3928     4201     4725     5164
1     1001     1034     1039     1044     1055
2     7255     7322     7420     7606     7735
3      780      781      781      781      789
4       41       42       61       61       64

[5 rows x 150 columns]

In [100]:
deaths_data_frame = pd.read_csv(deaths_dataset_url)
print(deaths_data_frame.head())

  Province/State Country/Region      Lat     Long  1/22/20  1/23/20  1/24/20  \
0            NaN    Afghanistan  33.0000  65.0000        0        0        0
1            NaN        Albania  41.1533  20.1683        0        0        0
2            NaN        Algeria  28.0339   1.6596        0        0        0
3            NaN        Andorra  42.5063   1.5218        0        0        0
4            NaN         Angola -11.2027  17.8739        0        0        0

   1/25/20  1/26/20  1/27/20  ...  6/6/20  6/7/20  6/8/20  6/9/20  6/10/20  \
0        0        0        0  ...     327     357     369     384      405
1        0        0        0  ...      34      34      34      34       34
2        0        0        0  ...     698     707     715     724      732
3        0        0        0  ...      51      51      51      51       51
4        0        0        0  ...       4       4       4       4        4

   6/11/20  6/12/20  6/13/20  6/14/20  6/15/20
0      426      446      451      471      478
1       35       36       36       36       36
2      741      751      760      767      777
3       51       51       51       51       51
4        5        5        6        6        6

[5 rows x 150 columns]

In [101]:
# total_infected_by_country = infected_data_frame.groupby('Country/Region').sum()
total_infected_by_country = infected_data_frame.groupby('Country/Region').sum().iloc[:, 3:].transpose()
print(total_infected_by_country)

Country/Region  Afghanistan  Albania  Algeria  Andorra  Angola  \
1/23/20                   0        0        0        0       0
1/24/20                   0        0        0        0       0
1/25/20                   0        0        0        0       0
1/26/20                   0        0        0        0       0
1/27/20                   0        0        0        0       0
...                     ...      ...      ...      ...     ...
6/11/20               22890     1385    10589      852     118
6/12/20               23546     1416    10698      853     130
6/13/20               24102     1464    10810      853     138
6/14/20               24766     1521    10919      853     140
6/15/20               25527     1590    11031      853     142

Country/Region  Antigua and Barbuda  Argentina  Armenia  Australia  Austria  \
1/23/20                           0          0        0          0        0
1/24/20                           0          0        0          0        0
1/25/20                           0          0        0          0        0
1/26/20                           0          0        0          4        0
1/27/20                           0          0        0          5        0
...                             ...        ...      ...        ...      ...
6/11/20                          26      27373    14669       7289    17034
6/12/20                          26      28764    15281       7294    17064
6/13/20                          26      30295    16004       7320    17078
6/14/20                          26      31577    16667       7335    17109
6/15/20                          26      32785    17064       7347    17135

Country/Region  ...  United Kingdom  Uruguay  Uzbekistan  Venezuela  Vietnam  \
1/23/20         ...               0        0           0          0        2
1/24/20         ...               0        0           0          0        2
1/25/20         ...               0        0           0          0        2
1/26/20         ...               0        0           0          0        2
1/27/20         ...               0        0           0          0        2
...             ...             ...      ...         ...        ...      ...
6/11/20         ...          292860      847        4741       2814      332
6/12/20         ...          294402      847        4869       2879      333
6/13/20         ...          295828      847        4966       2904      334
6/14/20         ...          297342      848        5080       2978      334
6/15/20         ...          298315      848        5263       3062      334

Country/Region  West Bank and Gaza  Western Sahara  Yemen  Zambia  Zimbabwe
1/23/20                          0               0      0       0         0
1/24/20                          0               0      0       0         0
1/25/20                          0               0      0       0         0
1/26/20                          0               0      0       0         0
1/27/20                          0               0      0       0         0
...                            ...             ...    ...     ...       ...
6/11/20                        487               9    591    1200       332
6/12/20                        489               9    632    1321       343
6/13/20                        489               9    705    1357       356
6/14/20                        492               9    728    1358       383
6/15/20                        505               9    844    1382       387

[145 rows x 188 columns]

In [102]:
total_recovered_by_country = recovered_data_frame.groupby('Country/Region').sum().iloc[:, 3:].transpose()
print(total_recovered_by_country)

Country/Region  Afghanistan  Albania  Algeria  Andorra  Angola  \
1/23/20                   0        0        0        0       0
1/24/20                   0        0        0        0       0
1/25/20                   0        0        0        0       0
1/26/20                   0        0        0        0       0
1/27/20                   0        0        0        0       0
...                     ...      ...      ...      ...     ...
6/11/20                3326     1001     7255      780      41
6/12/20                3928     1034     7322      781      42
6/13/20                4201     1039     7420      781      61
6/14/20                4725     1044     7606      781      61
6/15/20                5164     1055     7735      789      64

Country/Region  Antigua and Barbuda  Argentina  Armenia  Australia  Austria  \
1/23/20                           0          0        0          0        0
1/24/20                           0          0        0          0        0
1/25/20                           0          0        0          0        0
1/26/20                           0          0        0          0        0
1/27/20                           0          0        0          0        0
...                             ...        ...      ...        ...      ...
6/11/20                          20       8332     5466       6782    15949
6/12/20                          20       8743     5639       6803    15985
6/13/20                          20       9083     6081       6838    16012
6/14/20                          20       9564     6214       6851    16059
6/15/20                          20       9891     6276       6856    16066

Country/Region  ...  United Kingdom  Uruguay  Uzbekistan  Venezuela  Vietnam  \
1/23/20         ...               0        0           0          0        0
1/24/20         ...               0        0           0          0        0
1/25/20         ...               0        0           0          0        0
1/26/20         ...               0        0           0          0        0
1/27/20         ...               0        0           0          0        0
...             ...             ...      ...         ...        ...      ...
6/11/20         ...            1278      772        3637        487      321
6/12/20         ...            1282      780        3758        487      323
6/13/20         ...            1283      784        3874        487      323
6/14/20         ...            1283      788        3943        835      323
6/15/20         ...            1284      792        4019        835      323

Country/Region  West Bank and Gaza  Western Sahara  Yemen  Zambia  Zimbabwe
1/23/20                          0               0      0       0         0
1/24/20                          0               0      0       0         0
1/25/20                          0               0      0       0         0
1/26/20                          0               0      0       0         0
1/27/20                          0               0      0       0         0
...                            ...             ...    ...     ...       ...
6/11/20                        410               6     23     912        51
6/12/20                        414               6     28    1104        51
6/13/20                        415               8     39    1104        54
6/14/20                        415               8     53    1122        54
6/15/20                        415               8     79    1142        54

[145 rows x 188 columns]

In [103]:
total_deaths_by_country = deaths_data_frame.groupby('Country/Region').sum().iloc[:, 3:].transpose()
print(total_deaths_by_country)

Country/Region  Afghanistan  Albania  Algeria  Andorra  Angola  \
1/23/20                   0        0        0        0       0
1/24/20                   0        0        0        0       0
1/25/20                   0        0        0        0       0
1/26/20                   0        0        0        0       0
1/27/20                   0        0        0        0       0
...                     ...      ...      ...      ...     ...
6/11/20                 426       35      741       51       5
6/12/20                 446       36      751       51       5
6/13/20                 451       36      760       51       6
6/14/20                 471       36      767       51       6
6/15/20                 478       36      777       51       6

Country/Region  Antigua and Barbuda  Argentina  Armenia  Australia  Austria  \
1/23/20                           0          0        0          0        0
1/24/20                           0          0        0          0        0
1/25/20                           0          0        0          0        0
1/26/20                           0          0        0          0        0
1/27/20                           0          0        0          0        0
...                             ...        ...      ...        ...      ...
6/11/20                           3        765      245        102      674
6/12/20                           3        785      258        102      675
6/13/20                           3        815      264        102      677
6/14/20                           3        833      269        102      677
6/15/20                           3        854      285        102      678

Country/Region  ...  United Kingdom  Uruguay  Uzbekistan  Venezuela  Vietnam  \
1/23/20         ...               0        0           0          0        0
1/24/20         ...               0        0           0          0        0
1/25/20         ...               0        0           0          0        0
1/26/20         ...               0        0           0          0        0
1/27/20         ...               0        0           0          0        0
...             ...             ...      ...         ...        ...      ...
6/11/20         ...           41364       23          19         23        0
6/12/20         ...           41566       23          19         23        0
6/13/20         ...           41747       23          19         24        0
6/14/20         ...           41783       23          19         25        0
6/15/20         ...           41821       23          19         26        0

Country/Region  West Bank and Gaza  Western Sahara  Yemen  Zambia  Zimbabwe
1/23/20                          0               0      0       0         0
1/24/20                          0               0      0       0         0
1/25/20                          0               0      0       0         0
1/26/20                          0               0      0       0         0
1/27/20                          0               0      0       0         0
...                            ...             ...    ...     ...       ...
6/11/20                          3               1    136      10         4
6/12/20                          3               1    139      10         4
6/13/20                          3               1    160      10         4
6/14/20                          3               1    164      11         4
6/15/20                          3               1    208      11         4

[145 rows x 188 columns]

In [106]:
#Veri seti birleştirildi concat ile
birlestirilmis_data_frame = pd.concat([infected_data_frame, recovered_data_frame, deaths_data_frame], keys=["Infected", "Recovered", "Deaths"])
print(birlestirilmis_data_frame)

             Province/State         Country/Region        Lat       Long  \
Infected 0              NaN            Afghanistan  33.000000  65.000000
         1              NaN                Albania  41.153300  20.168300
         2              NaN                Algeria  28.033900   1.659600
         3              NaN                Andorra  42.506300   1.521800
         4              NaN                 Angola -11.202700  17.873900
...                     ...                    ...        ...        ...
Deaths   261            NaN  Sao Tome and Principe   0.186360   6.613081
         262            NaN                  Yemen  15.552727  48.516388
         263            NaN                Comoros -11.645500  43.333300
         264            NaN             Tajikistan  38.861034  71.276093
         265            NaN                Lesotho -29.609988  28.233608

              1/22/20  1/23/20  1/24/20  1/25/20  1/26/20  1/27/20  ...  \
Infected 0          0        0        0        0        0        0  ...
         1          0        0        0        0        0        0  ...
         2          0        0        0        0        0        0  ...
         3          0        0        0        0        0        0  ...
         4          0        0        0        0        0        0  ...
...               ...      ...      ...      ...      ...      ...  ...
Deaths   261        0        0        0        0        0        0  ...
         262        0        0        0        0        0        0  ...
         263        0        0        0        0        0        0  ...
         264        0        0        0        0        0        0  ...
         265        0        0        0        0        0        0  ...

              6/6/20  6/7/20  6/8/20  6/9/20  6/10/20  6/11/20  6/12/20  \
Infected 0     19551   20342   20917   21459    22142    22890    23546
         1      1232    1246    1263    1299     1341     1385     1416
         2     10050   10154   10265   10382    10484    10589    10698
         3       852     852     852     852      852      852      853
         4        88      91      92      96      113      118      130
...              ...     ...     ...     ...      ...      ...      ...
Deaths   261      12      12      12      12       12       12       12
         262     111     112     112     127      129      136      139
         263       2       2       2       2        2        2        2
         264      48      48      48      48       48       49       49
         265       0       0       0       0        0        0        0

              6/13/20  6/14/20  6/15/20
Infected 0      24102    24766    25527
         1       1464     1521     1590
         2      10810    10919    11031
         3        853      853      853
         4        138      140      142
...               ...      ...      ...
Deaths   261       12       12       12
         262      160      164      208
         263        2        2        2
         264       50       50       50
         265        0        0        0

[785 rows x 150 columns]

In [107]:
# Province/State sütunundaki None değerler fillna ile dolduruldu
birlestirilmis_data_frame["Province/State"].fillna("Yok", inplace=True)# inplace false ise orjinal DataFrame değişmeden kalır ve değişiklikler yeni bir DataFrame'e uygulanır
print(birlestirilmis_data_frame)

             Province/State         Country/Region        Lat       Long  \
Infected 0              Yok            Afghanistan  33.000000  65.000000
         1              Yok                Albania  41.153300  20.168300
         2              Yok                Algeria  28.033900   1.659600
         3              Yok                Andorra  42.506300   1.521800
         4              Yok                 Angola -11.202700  17.873900
...                     ...                    ...        ...        ...
Deaths   261            Yok  Sao Tome and Principe   0.186360   6.613081
         262            Yok                  Yemen  15.552727  48.516388
         263            Yok                Comoros -11.645500  43.333300
         264            Yok             Tajikistan  38.861034  71.276093
         265            Yok                Lesotho -29.609988  28.233608

              1/22/20  1/23/20  1/24/20  1/25/20  1/26/20  1/27/20  ...  \
Infected 0          0        0        0        0        0        0  ...
         1          0        0        0        0        0        0  ...
         2          0        0        0        0        0        0  ...
         3          0        0        0        0        0        0  ...
         4          0        0        0        0        0        0  ...
...               ...      ...      ...      ...      ...      ...  ...
Deaths   261        0        0        0        0        0        0  ...
         262        0        0        0        0        0        0  ...
         263        0        0        0        0        0        0  ...
         264        0        0        0        0        0        0  ...
         265        0        0        0        0        0        0  ...

              6/6/20  6/7/20  6/8/20  6/9/20  6/10/20  6/11/20  6/12/20  \
Infected 0     19551   20342   20917   21459    22142    22890    23546
         1      1232    1246    1263    1299     1341     1385     1416
         2     10050   10154   10265   10382    10484    10589    10698
         3       852     852     852     852      852      852      853
         4        88      91      92      96      113      118      130
...              ...     ...     ...     ...      ...      ...      ...
Deaths   261      12      12      12      12       12       12       12
         262     111     112     112     127      129      136      139
         263       2       2       2       2        2        2        2
         264      48      48      48      48       48       49       49
         265       0       0       0       0        0        0        0

              6/13/20  6/14/20  6/15/20
Infected 0      24102    24766    25527
         1       1464     1521     1590
         2      10810    10919    11031
         3        853      853      853
         4        138      140      142
...               ...      ...      ...
Deaths   261       12       12       12
         262      160      164      208
         263        2        2        2
         264       50       50       50
         265        0        0        0

[785 rows x 150 columns]

In [108]:
# Country/Region ve Province/State'e göre gruplanarak toplam vaka sayısı bulundu
toplam_vaka_sayisi = birlestirilmis_data_frame.groupby(["Country/Region", "Province/State"]).sum()
print(toplam_vaka_sayisi)

                                          Lat        Long  1/22/20  1/23/20  \
Country/Region     Province/State
Afghanistan        Yok              99.000000  195.000000        0        0
Albania            Yok             123.459900   60.504900        0        0
Algeria            Yok              84.101700    4.978800        0        0
Andorra            Yok             127.518900    4.565400        0        0
Angola             Yok             -33.608100   53.621700        0        0
...                                       ...         ...      ...      ...
West Bank and Gaza Yok              95.856600  105.699600        0        0
Western Sahara     Yok              72.646500  -38.657400        0        0
Yemen              Yok              46.658181  145.549164        0        0
Zambia             Yok             -46.250100   84.849900        0        0
Zimbabwe           Yok             -60.000000   90.000000        0        0

                                   1/24/20  1/25/20  1/26/20  1/27/20  \
Country/Region     Province/State
Afghanistan        Yok                   0        0        0        0
Albania            Yok                   0        0        0        0
Algeria            Yok                   0        0        0        0
Andorra            Yok                   0        0        0        0
Angola             Yok                   0        0        0        0
...                                    ...      ...      ...      ...
West Bank and Gaza Yok                   0        0        0        0
Western Sahara     Yok                   0        0        0        0
Yemen              Yok                   0        0        0        0
Zambia             Yok                   0        0        0        0
Zimbabwe           Yok                   0        0        0        0

                                   1/28/20  1/29/20  ...  6/6/20  6/7/20  \
Country/Region     Province/State                    ...
Afghanistan        Yok                   0        0  ...   21708   22574
Albania            Yok                   0        0  ...    2191    2218
Algeria            Yok                   0        0  ...   17379   17578
Andorra            Yok                   0        0  ...    1644    1647
Angola             Yok                   0        0  ...     116     119
...                                    ...      ...  ...     ...     ...
West Bank and Gaza Yok                   0        0  ...     867     878
Western Sahara     Yok                   0        0  ...      16      16
Yemen              Yok                   0        0  ...     616     619
Zambia             Yok                   0        0  ...    2008    2008
Zimbabwe           Yok                   0        0  ...     316     320

                                   6/8/20  6/9/20  6/10/20  6/11/20  6/12/20  \
Country/Region     Province/State
Afghanistan        Yok              23457   24494    25560    26642    27920
Albania            Yok               2242    2293     2355     2421     2486
Algeria            Yok              17779   18057    18290    18585    18771
Andorra            Yok               1654    1660     1662     1683     1685
Angola             Yok                134     138      157      164      177
...                                   ...     ...      ...      ...      ...
West Bank and Gaza Yok                880     888      898      900      906
Western Sahara     Yok                 16      16       16       16       16
Yemen              Yok                631     674      712      750      799
Zambia             Yok               2122    2122     2122     2122     2435
Zimbabwe           Yok                337     364      373      387      398

                                   6/13/20  6/14/20  6/15/20
Country/Region     Province/State
Afghanistan        Yok               28754    29962    31169
Albania            Yok                2539     2601     2681
Algeria            Yok               18990    19292    19543
Andorra            Yok                1685     1685     1693
Angola             Yok                 205      207      212
...                                    ...      ...      ...
West Bank and Gaza Yok                 907      910      923
Western Sahara     Yok                  18       18       18
Yemen              Yok                 904      945     1131
Zambia             Yok                2471     2491     2535
Zimbabwe           Yok                 414      441      445

[267 rows x 148 columns]

In [109]:
sorted_total_cases = toplam_vaka_sayisi.sort_values(by="Country/Region", ascending=False)
print(sorted_total_cases)

                                          Lat        Long  1/22/20  1/23/20  \
Country/Region     Province/State
Zimbabwe           Yok             -60.000000   90.000000        0        0
Zambia             Yok             -46.250100   84.849900        0        0
Yemen              Yok              46.658181  145.549164        0        0
Western Sahara     Yok              72.646500  -38.657400        0        0
West Bank and Gaza Yok              95.856600  105.699600        0        0
...                                       ...         ...      ...      ...
Angola             Yok             -33.608100   53.621700        0        0
Andorra            Yok             127.518900    4.565400        0        0
Algeria            Yok              84.101700    4.978800        0        0
Albania            Yok             123.459900   60.504900        0        0
Afghanistan        Yok              99.000000  195.000000        0        0

                                   1/24/20  1/25/20  1/26/20  1/27/20  \
Country/Region     Province/State
Zimbabwe           Yok                   0        0        0        0
Zambia             Yok                   0        0        0        0
Yemen              Yok                   0        0        0        0
Western Sahara     Yok                   0        0        0        0
West Bank and Gaza Yok                   0        0        0        0
...                                    ...      ...      ...      ...
Angola             Yok                   0        0        0        0
Andorra            Yok                   0        0        0        0
Algeria            Yok                   0        0        0        0
Albania            Yok                   0        0        0        0
Afghanistan        Yok                   0        0        0        0

                                   1/28/20  1/29/20  ...  6/6/20  6/7/20  \
Country/Region     Province/State                    ...
Zimbabwe           Yok                   0        0  ...     316     320
Zambia             Yok                   0        0  ...    2008    2008
Yemen              Yok                   0        0  ...     616     619
Western Sahara     Yok                   0        0  ...      16      16
West Bank and Gaza Yok                   0        0  ...     867     878
...                                    ...      ...  ...     ...     ...
Angola             Yok                   0        0  ...     116     119
Andorra            Yok                   0        0  ...    1644    1647
Algeria            Yok                   0        0  ...   17379   17578
Albania            Yok                   0        0  ...    2191    2218
Afghanistan        Yok                   0        0  ...   21708   22574

                                   6/8/20  6/9/20  6/10/20  6/11/20  6/12/20  \
Country/Region     Province/State
Zimbabwe           Yok                337     364      373      387      398
Zambia             Yok               2122    2122     2122     2122     2435
Yemen              Yok                631     674      712      750      799
Western Sahara     Yok                 16      16       16       16       16
West Bank and Gaza Yok                880     888      898      900      906
...                                   ...     ...      ...      ...      ...
Angola             Yok                134     138      157      164      177
Andorra            Yok               1654    1660     1662     1683     1685
Algeria            Yok              17779   18057    18290    18585    18771
Albania            Yok               2242    2293     2355     2421     2486
Afghanistan        Yok              23457   24494    25560    26642    27920

                                   6/13/20  6/14/20  6/15/20
Country/Region     Province/State
Zimbabwe           Yok                 414      441      445
Zambia             Yok                2471     2491     2535
Yemen              Yok                 904      945     1131
Western Sahara     Yok                  18       18       18
West Bank and Gaza Yok                 907      910      923
...                                    ...      ...      ...
Angola             Yok                 205      207      212
Andorra            Yok                1685     1685     1693
Algeria            Yok               18990    19292    19543
Albania            Yok                2539     2601     2681
Afghanistan        Yok               28754    29962    31169

[267 rows x 148 columns]